<?xml version="1.0"?>
<package format="2">
  <name>super_grasp</name>
  <version>1.0.0</version>
  <description>The super_grasp package - C++ implementation</description>

  <license>NA</license>

  <maintainer email="jkanbour1@gmail.com">Jayden Kanbour</maintainer>
  <author email="jkanbour1@gmail.com">Jayden Kanbour</author>

  <!-- Build tool -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- Build dependencies -->
  <build_depend>roscpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_depend>tf</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_depend>tf2_geometry_msgs</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>unsw_vision_msgs</build_depend>
  <build_depend>image_transport</build_depend>
  <build_depend>eigen</build_depend>
  <build_depend>libopenCV-dev</build_depend>

  <!-- Runtime dependencies -->
  <exec_depend>roscpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>unsw_vision_msgs</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>eigen</exec_depend>
  <exec_depend>libopenCV</exec_depend>

  <export/>
</package>